#!/usr/bin/env node
const Commands = require("./dist/commands/commands").default;
const packageJson = require('./package');

new Commands(packageJson).init([
    {
        event: {
            name: '--help',
            action: () => console.log('help')
        }
    },
    {
        command: 'exec <cmd>',
        description: 'execute the given remote cmd',
        alias: 'ex',
        option: {
            flag: '-e, --exec_mode <mode>',
            description: 'Whitch exec mode to use'
        },
        action: (cmd, options) => {
            if (options.exec_mode !== undefined)
                console.log(`exec '${cmd}' using '${options.exec_mode}' mode`);
        },
        event: {
            name: '--help',
            action: () => console.log(`
    Examples: 
        
    $ deploy exec sequential
    $ deploy exec async`)
        }
    },
    {
        command: '*',
        action: env => console.log(`deploying `, env)
    }
]).start(process.argv);